import numpy as np
import torch
import os


def saveObj(filename, materialName, vertices, faces, normals=None, tcoords=None, textureFileName='texture.png'):
    '''
    write mesh to an obj file
    :param filename: path to where to save the obj file
    :param materialFileName: material name
    :param vertices:  float tensor [n, 3]
    :param faces: tensor [#triangles, 3]
    :param normals: float tensor [n, 3]
    :param tcoords: float tensor [n, 2]
    :param textureFileName: name of the texture to use with material
    :return:
    '''
    assert(vertices.dim() == 2 and  vertices.shape[-1] == 3)
    assert (faces.dim() == 2 and faces.shape[-1] == 3)

    if normals is not None:
        assert (normals.dim() == 2 and normals.shape[-1] == 3)

    if tcoords is not None:
        assert (tcoords.dim() == 2 and tcoords.shape[-1] == 2)

    if torch.is_tensor(vertices):
        vertices = vertices.detach().cpu().numpy()
    if torch.is_tensor(faces):
        faces = faces.detach().cpu().numpy()
    if torch.is_tensor(normals):
        normals = normals.detach().cpu().numpy()
    if torch.is_tensor(tcoords):
        tcoords = tcoords.detach().cpu().numpy()

    assert(isinstance(vertices, np.ndarray))
    assert (isinstance(faces, np.ndarray))
    assert (isinstance(normals, np.ndarray))
    assert (isinstance(tcoords, np.ndarray))

    #write material
    with open(os.path.dirname(filename) + '/' + materialName, 'w') as f:
        f.write('newmtl material0\n')
        f.write('map_Kd ' + textureFileName + '\n')

    with open(filename, 'w') as f:
        f.write('###########################################################\n')
        f.write('# OBJ file generated by faceYard 2021\n')
        f.write('#\n')
        f.write('# Num Vertices: %d\n' % (vertices.shape[0]))
        f.write('# Num Triangles: %d\n' % (faces.shape[0]))
        f.write('#\n')
        f.write('###########################################################\n')
        f.write('\n')
        f.write('mtllib ' + materialName + '\n')

        #write vertices
        for v in vertices:
            f.write('v %f %f %f\n' % (v[0], v[1], v[2]))

        # write the tcoords
        if tcoords is not None and tcoords.shape[0] > 0:
            for uv in tcoords:
                f.write('vt %f %f\n' % (uv[0], uv[1]))

        #write the normals
        if normals is not None and normals.shape[0] > 0:
            for n in normals:
                f.write('vn %f %f %f\n' % (n[0], n[1], n[2]))

        f.write('usemtl material0\n')
        #write face indices list
        for t in faces:
            f.write('f %d/%d/%d %d/%d/%d %d/%d/%d\n' % (t[0] + 1, t[0] + 1,t[0] + 1,
                                                  t[1] + 1, t[1] + 1,t[1] + 1,
                                                  t[2] + 1, t[2] + 1, t[2] + 1))
